Bug fix issue 118
nautobot/nautobot-plugin-device-lifecycle-mgmt pull request #119
Opened 2022-11-13 22:46 UTC by bradh11

This bug fix addresses an issue which requires `["barchart_bar_width", "barchart_width", "barchart_height"]` to be present in `nautobot_config.py`.  There are default settings in the package `__init__.py` which are now honored, but not required to be in the config file.

2022-11-14 08:53 UTC, bradh11 commented
Looks like tests work from my local dev environment but are failing in CI.  We will need to determine why before approving this PR.

2022-11-15 02:00 UTC, jvanderaa approved these changes

2022-11-15 18:05 UTC, progala requested changes
Looks good. Just a few suggestions and then we should be good to go.

2022-11-15 18:05 UTC, progala commented on tasks.py
> +    command = "pydocstyle ."
```suggestion
    command = "pydocstyle --config=.pydocstyle.ini ."
```

2022-11-16 18:25 UTC, bradh11 commented on development/nautobot_config.py
> +    "nautobot_device_lifecycle_mgmt": {},
ok, sounds good.  We will also need to update the README and docs so that it doesn't make it seem these are required anymore.

2022-11-18 16:32 UTC, progala commented
LGTM

2022-11-21 21:40 UTC, merged