Prometheus Metrics
nautobot/nautobot-plugin-device-lifecycle-mgmt pull request #148
Opened 2023-03-25 00:06 UTC by alhogan

@zackt25 and I added some basic metrics for Lifecycle Management.

```shell
# HELP nautobot_lcm_valid_by_device_type_total Number of devices that have valid software by device_type
# TYPE nautobot_lcm_valid_by_device_type_total gauge

# HELP nautobot_lcm_invalid_by_device_type_total Number of devices that have invalid software by device_type
# TYPE nautobot_lcm_invalid_by_device_type_total gauge

# HELP nautobot_lcm_valid_by_inventory_item_total Number of devices that have valid software by inventory item
# TYPE nautobot_lcm_valid_by_inventory_item_total gauge

# HELP nautobot_lcm_invalid_by_inventory_item_total Number of devices that have invalid software by inventory item
# TYPE nautobot_lcm_invalid_by_inventory_item_total gauge

# HELP nautobot_lcm_device_result_total Number of devices that are in lifecycle management report
# TYPE nautobot_lcm_device_result_total gauge
nautobot_lcm_device_result_total{devices="Total LCM Validated Device Count"} 0.0
# HELP nautobot_lcm_inventory_result_total Number of inventory items that are in lifecycle management report
# TYPE nautobot_lcm_inventory_result_total gauge

```

Closes #143

2023-03-31 09:12 UTC, progala commented
@bradh11 Sure, I'll have a look today.

2023-03-31 22:25 UTC, jvanderaa commented
We should look to take nautobot out all together on pyproject.toml if doing anything to it. 


Is there something in particular that we need to be at 1.5.13??

Let's also remove the changes to the migration files.

2023-04-04 15:24 UTC, alhogan commented
I suspect adding `nautobot-capacity-metrics` as a dependency is what caused the flake8 downgrade. I'm happy to remove the changes outside of `metrics.py` but my understanding is that the metrics will not be available without nautobot >= 1.5.13 and the capacity metrics plugin.

2023-04-04 16:01 UTC, alhogan reviewed
All changes outside of `metrics.py` have been reverted

2023-04-05 12:21 UTC, Kircheneer requested changes

2023-04-05 12:21 UTC, Kircheneer commented on nautobot_device_lifecycle_mgmt/metrics.py
> +    )
My vote would be to put both of these into one metric and have a valid/invalid label instead.

2023-04-05 12:21 UTC, Kircheneer commented on nautobot_device_lifecycle_mgmt/metrics.py
> +        )
> if not no gauge will be created

According to [best practices](https://prometheus.io/docs/practices/instrumentation/#avoid-missing-metrics) you should _always_ provide a metric, even if the sample is just set to 0 and no labels are present.

2023-04-05 12:21 UTC, Kircheneer commented on nautobot_device_lifecycle_mgmt/metrics.py
> +    )
I would vote to also condense these into one metric through an additional label

2023-04-05 12:21 UTC, Kircheneer commented on nautobot_device_lifecycle_mgmt/metrics.py
> +        )
Also needs a case for `inventory_item_validation = []`

2023-04-05 12:21 UTC, Kircheneer commented on nautobot_device_lifecycle_mgmt/metrics.py
> +    yield total_inventory_item_software_gauge
Counting of model instances should be available in core directly whenever I get [this PR](https://github.com/nautobot/nautobot-plugin-capacity-metrics/pull/46) merged into core - so this metric is not necessary.

2023-04-05 14:16 UTC, progala commented
@alhogan @Kircheneer My understanding is that if you're running Nautobot < 1.5.13 you simply won't have access to the metrics but the plugins should still work. If that's the case we should keep the minimum requirement at 1.4.0 and make sure docs and release notes explain what's required to have metrics.

2023-05-15 09:32 UTC, progala commented
I'm working on PR which will use querysets instead of loops. One question I have is around the treatment of inventory items that have no part_id defined, i.e. where the value of part_id is an empty string. Should we exclude those completely from the queries? @alhogan @Kircheneer @nkallergis

2023-05-15 10:01 UTC, nkallergis commented
That would be my approach since (if I'm not mistaken) there's no means to assign an LCM notice on them. That said, keep in mind that the other PR (#151, now merged) did include them.

2023-05-17 08:29 UTC, progala commented
@alhogan @nkallergis @Kircheneer I've converted the logic to use the query annotations. I'd be grateful if you could review the PR as it is now and we'll hopefully be able to merge it soon.

2023-06-01 06:23 UTC, nkallergis approved these changes
That's actually wonderful and so easy to read! Makes me think that a) I need to learn better Django and b) maybe we need to revisit the metrics implementation of other plugins to align with this approach 🤔

2023-06-01 06:37 UTC, Kircheneer approved these changes
LGTM

2023-06-01 09:44 UTC, merged