Fix Reports
nautobot/nautobot-plugin-device-lifecycle-mgmt pull request #84
Opened 2022-04-08 20:11 UTC by jdrew82

This PR should make the required changes to fix #83.

2022-04-08 20:26 UTC, jvanderaa requested changes

2022-04-08 20:26 UTC, jvanderaa commented on nautobot_device_lifecycle_mgmt/__init__.py
>      default_settings = {"expired_field": "end_of_support"}
@jdrew82 can we add those defaults here as well?

2022-04-08 20:34 UTC, jvanderaa approved these changes

2022-04-14 18:56 UTC, jvanderaa commented
@progala @josh-silvas what are the thoughts here?

2022-04-19 11:08 UTC, progala commented
LGTM. Thanks @jdrew82 !

2022-04-19 11:08 UTC, progala approved these changes
LGTM

2022-04-29 16:40 UTC, merged